name: bizgrow_mobile_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/navbar_icon/default/Beranda.png
    - lib/assets/navbar_icon/default/Penjualan.png
    - lib/assets/navbar_icon/default/Stok.png
    - lib/assets/navbar_icon/default/Profil.png
    - lib/assets/navbar_icon/selected/Beranda.png
    - lib/assets/navbar_icon/selected/Penjualan.png
    - lib/assets/navbar_icon/selected/Stok.png
    - lib/assets/navbar_icon/selected/Profil.png
